 set hlsearch                                                                                                                                                                                                                                                                   
 hi Search ctermbg=White ctermfg=Black                                                                                                                                                                                                                                          
 nnoremap <Space> :noh<CR>                                                                                                                                                                                                                                                      
 let g:ale_linters = {'python': ['pylint'],                                                                                                                                                                                                                                     
         \ 'yaml' : ['cloudformation']}                                                                                                                                                                                                                                         
 set nocompatible                                                                                                                                                                                                                                                               
 filetype plugin on                                                                                                                                                                                                                                                             
 syntax on                                                                                                                                                                                                                                                                      
 set tabstop=2 softtabstop=0 expandtab shiftwidth=2 smarttab  
